/// A simulator for my Turing Complete game's LEG (EX) architecture.
/// This consumes a file of line-broken integer 'machine code' and runs it as an executable.
/// Code files are the ones generated by legasm.py.
/// 
/// Specification date: 12/24/2023
/// 
/// Options are documented in --help, and commands are documented in the 'help' command.
/// Keep in mind to set the text mode on or off properly, as many programs assume text mode.
/// 
/// All instructions take exactly one cycle, which is very nearly true in the game as well.

use clap::Parser;
#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct Args {
    /// The program file name to run.
    program: String,

    /// Whether to run in 'text mode'.
    #[arg(short, long)]
    text_mode: bool
}

fn main() {
    let args = Args::parse();

    println!("{:?}", args);
}